{% raw -%}
defaults:
  onFailure:
    report:
      sentry:
        dsn:
          fromEnvVar: SENTRY_DSN
        fingerprint:  # optional, since yacron 0.6
          - '{{ name }}'
  utc: false
  captureStdout: true
  captureStderr: true
  concurrencyPolicy: Forbid
  failsWhen:
    producesStdout: false
    producesStderr: false
{% endraw -%}
jobs:
  - name: {{ cookiecutter.django_command_name }}
    schedule:
      minute: '*/5'
    command: django-admin {{ cookiecutter.django_command_name }}
