{% raw -%}
- hosts: 127.0.0.1
  connection: local
  tags: [build]
  tasks:
    - name: start registry
      docker_compose:
        project_name: registry
        remove_orphans: yes
        definition:
          version: '3.7'
          services: >
            {
              "{{ compose_project_name }}": {
                "image": "registry:2",
                "ports": ["{{ registry_port }}:5000"],
                "volumes": ["{{ playbook_dir }}/../.home/registry:/var/lib/registry"]
              }
            }
    - name: build and publish image
      command:
        chdir: ..
        cmd: docker compose --file {{ inventory_dir }}/docker-compose.build.yml {{ item }}
      environment:
        app_version: '{{ app_version }}'
        registry_host: '{{ registry_host }}'
        compose_project_name: '{{ compose_project_name }}'
        django_settings_module: '{{ django_settings_module }}'
      loop:
        - build
        - push
- hosts: all
  tasks:
    - name: log deployment
      tags: [always]
      lineinfile:
        create: true
        dest: /services/deploy.log
        line: ===== {{ inventory_dir|basename }} deploy @ {{ now() }} =====
    - name: copy release docker-compose.yml
      template:
        src: '{{ inventory_dir }}/docker-compose.release.yml'
        dest: '/services/{{ compose_file }}'
    - name: get available compose files
      tags: [always]
      find:
        paths: /services
        patterns: docker-compose*.yml
      register: compose_files_register
- hosts: all
  vars:
    compose_files: '{{ compose_files_register.files | map(attribute="path") | join(":") }}'
  environment:
    COMPOSE_FILE: '{{ compose_files }}'
  tasks:
    - name: set default docker-compose.yml in environment
      tags: [env]
      lineinfile:
        dest: /etc/environment
        regexp: '^COMPOSE_FILE='
        line: 'COMPOSE_FILE={{ compose_files|quote }}'
    - name: ensure new users/databases
      when: database_name is defined
      shell:
        executable: /bin/bash
        cmd: |
          exec > >(tee -a /services/deploy.log) 2>&1
          set -euxo pipefail
          docker compose exec -T -e POSTGRES_EXTRAS={{ database_name }} pg /docker-entrypoint-initdb.d/extra-users.sh
    - name: run migrations
      shell:
        executable: /bin/bash
        cmd: |
          set -euxo pipefail
          docker compose run --rm --no-TTY {{ item.key }} pysu app django-admin migrate --no-input
      loop: '{{ services|dict2items }}'
      when: item.value
    - name: run collectstatic
      shell:
        executable: /bin/bash
        cmd: |
          set -euxo pipefail
          docker compose run --rm --no-TTY {{ item.key }} pysu app django-admin collectstatic --noinput --clear -v0
      loop: '{{ services|dict2items }}'
      when: item.value
    - name: restart services
      tags: [restart, never]
      shell:
        executable: /bin/bash
        cmd: |
          exec > >(tee -a /services/deploy.log) 2>&1
          set -euxo pipefail
          docker compose restart {{ item }}
      loop: '{{ services|list }}'
    - name: start/update services
      tags: [restart]
      shell:
        executable: /bin/bash
        cmd: |
          exec > >(tee -a /services/deploy.log) 2>&1
          set -euxo pipefail
          docker compose up --detach --quiet-pull --no-color
    - name: reload nginx
      shell:
        executable: /bin/bash
        cmd: |
          set -euxo pipefail
          docker compose kill --signal HUP nginx
- hosts: 127.0.0.1
  connection: local
  tags: [build]
  tasks:
    - name: shutdown registry
      tags: [cleanup]
      docker_compose:
        project_name: registry
        state: absent
        remove_orphans: yes
        definition:
          version: '3.7'
          services: '{"{{ compose_project_name }}": {"image": "registry:2"}}'
{%- endraw %}
