# To install the git pre-commit hooks run:
#   pre-commit install --install-hooks
# To update the versions:
#   pre-commit autoupdate
exclude: '^(\.bumpversion\.cfg)(/|$)'

# Note the order is intentional to avoid multiple passes of the hooks:
# - django-upgrade produces broken formatting thus needs to run before black
# - ruff does refactor thus it probably produces broken formatting too
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: main
    hooks:
      - id: django-upgrade
        args: [ --target-version, "4.2" ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: main
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
  - repo: https://github.com/rtts/djhtml
    rev: main
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
