# To install the git pre-commit hooks run:
#   pre-commit install --install-hooks
# To update the versions:
#   pre-commit autoupdate
exclude: '^(\.bumpversion\.cfg)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
{%- if cookiecutter.pre_commit_formatter == 'black' %}
  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
{%- elif cookiecutter.pre_commit_formatter == 'blue' %}
  - repo: https://github.com/grantjenks/blue
    rev: master
    hooks:
      - id: blue
{%- endif %}
  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
