version: '{{ cookiecutter.docker_compose_version }}'

services:
  pg:
    ports:
      - '5432:5432'
  nginx:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: nginx
    environment:
      SERVER_NAME:
      PYTHONHUNTER:
      PYTHONHUNTERCONFIG:
      DJANGO_DEBUG:
      DJANGO_DEBUG_SQL:
      DJANGO_DEBUG_SQL_LIMIT:
      DJANGO_DEBUG_TOOLBAR:
    env_file:
      - .env
    tty: false
    volumes:
      - ./.home:/shared/${SERVER_NAME}
      - ./.home/nginx/etc:/etc/app
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    entrypoint: [ '/entrypoint.sh' ]
    command: [
      'holdup',
      '--verbose', 'unix:///shared/${SERVER_NAME}/run/uwsgi.sock',
      '--',
      'nginx',
    ]
  web:
    environment:
      DJANGO_DB_MIGRATE: y
      DJANGO_COLLECTSTATIC: y
    command: [
      'uwsgi',
      '--ini', '/etc/app/uwsgi.ini',
      '--processes', '4',
    ]
    depends_on:
      - pg
    stop_signal: SIGTERM
  reloader:
    build:
      context: docker/reloader
    volumes:
      - .:/app
      - ./.home:/var/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RELOADER_MONITOR:
      COMPOSE_PROJECT_NAME:
