version: '{{ cookiecutter.docker_compose_version }}'

x-python:
  &python
  build:
    context: .
    dockerfile: docker/python/Dockerfile
    args:
      REQUIREMENTS: base
      DJANGO_SETTINGS_MODULE:
      DJANGO_COLLECTSTATIC: x
  environment:
    PYTHONHUNTER:
    PYTHONHUNTERCONFIG:
    DJANGO_DEBUG:
    DJANGO_DEBUG_SQL:
    DJANGO_DEBUG_SQL_LIMIT:
    DJANGO_DEBUG_TOOLBAR:
    LOGGING_LEVEL:
    LOGGING_PATH:
  env_file:
    - .env
  tty: false
  deploy:
    resources:
      limits:
        memory: $MEMORY_LIMIT
  volumes:
    - .:/app
    - ./.home:/root
    - ./.home:/home/app
    - ./.home:/var/app
    - ./.home/etc:/etc/app
    - ./.home/logs:/app/logs
services:
  pg:
    build:
      context: docker/postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      PGDATA:
    command: [
      'postgres',
      '-c', 'log_lock_waits=true',
      '-c', 'log_min_error_statement=WARNING',
      '-c', 'log_min_duration_statement=1s',
    ]
    volumes:
      - .:/app
      - ./.home:/root

  mc:
    image: memcached:{{ cookiecutter.memcached_version }}

  redis:
    image: redis:{{ cookiecutter.redis_version }}

  cron:
    <<: *python
    depends_on:
      - pg
    entrypoint: [ '/entrypoint.sh' ]
    command: [ 'pysu', 'app', '--', 'yacron', '--config=/etc/app/yacron.yml' ]

  web:
    <<: *python
    depends_on:
      - pg
      - mc
      - redis
    entrypoint: [ '/entrypoint.sh' ]
{%- if cookiecutter.worker == "celery" %}

  worker:
    <<: *python
    entrypoint: [ '/entrypoint.sh' ]
    command: [
      'pysu', 'app', '--',
      'celery', '-A', '{{ cookiecutter.django_project_name }}', 'worker'
    ]
    depends_on:
      - pg
      - redis
{%- elif cookiecutter.worker == "rq" %}

  worker:
    <<: *python
    entrypoint: [ '/entrypoint.sh' ]
    command: [
      'pysu', 'app', '--',
      'django-admin', 'rqworker'
    ]
    depends_on:
      - pg
      - redis
    deploy:
      replicas: 2
{%- endif %}
