version: '{{ cookiecutter.docker_compose_version }}'

services:
  web:
    environment:
      DJANGO_DB_MIGRATE: y
    privileged: true
    ports:
      - '80:8000'
    command: [
      'django-admin',
      'runserver_plus',
      '--insecure',
      '--nopin',
      '0.0.0.0:8000'
    ]
    stop_signal: SIGINT
