{% if cookiecutter.pre_commit_formatter == 'black' -%}
[tool.black]
line-length = 140
target-version = ['py310']
skip-string-normalization = true
{%- elif cookiecutter.pre_commit_formatter == 'blue' -%}
[tool.blue]
line-length = 140
target-version = ['py310']
{%- endif %}
